/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jinstaller;

/**
 *
 * @author luis
 */
public class jDialogMessage extends javax.swing.JDialog {
    private ResultType ret_;
    public enum DialogType{
        OK_CANCEL,
        OK 
    }
    
    public enum ResultType{
        OK,
        CANCEL
    }
    
    /**
     * Creates new form jDialogMessage
     */
    private jDialogMessage(java.awt.Frame parent, boolean modal, 
            DialogType type, String message) {
        super(parent, modal);
        initComponents();
        
        if(type.equals(DialogType.OK)){
            jButtonCancel.setVisible(false);
        }
        setLocationRelativeTo(null);
        jLabelMessage.setText(message);
        ret_ = ResultType.CANCEL;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabelMessage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();

        setBackground(java.awt.Color.gray);
        setUndecorated(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelMessage.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelMessage.setText("%TEXT%");

        jPanel1.setMaximumSize(new java.awt.Dimension(300, 35));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 35));

        jButtonCancel.setText("Cancel");
        jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonCancelMousePressed(evt);
            }
        });
        jPanel1.add(jButtonCancel);

        jButtonOk.setText("OK");
        jButtonOk.setMaximumSize(new java.awt.Dimension(81, 25));
        jButtonOk.setMinimumSize(new java.awt.Dimension(81, 25));
        jButtonOk.setPreferredSize(new java.awt.Dimension(81, 25));
        jButtonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonOkMousePressed(evt);
            }
        });
        jPanel1.add(jButtonOk);

        jPanel2.add(jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOkMousePressed
        ret_ = ResultType.OK;
        setVisible(false);
    }//GEN-LAST:event_jButtonOkMousePressed

    private void jButtonCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelMousePressed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelMousePressed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    protected ResultType getResult(){
        return ret_;
    }
    
    public static ResultType show(javax.swing.JFrame parent,String message){
        return show(null, message,DialogType.OK);
    }
    public static ResultType show(javax.swing.JFrame parent,String message,
            DialogType type){
        jDialogMessage m = new jDialogMessage(parent, true, type, message);
        m.setVisible(true);
        return m.getResult();
        
    }
    
}
