/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jinstaller;

import org.jinstaller.util.Properties;
import org.jinstaller.panels.JPanelLicence;
import org.jinstaller.panels.JPanelStart;
import org.jinstaller.util.ImageUtil;
import org.jinstaller.util.MessageUtil;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import org.jinstaller.panels.JPanelFolderSelection;

/**
 *
 * @author luis
 */
public class Main extends javax.swing.JFrame implements MainInstaller {

    int pointer = 0;
    List<InstallerFase> fases;
    JPanel actualPanel;
    boolean locked = false;
    ImageIcon leftImage = null;

    /**
     * Creates new form Main
     */
    public Main() {

        leftImage = ImageUtil.getRelativeImageIcon(Properties.getPropertie("left-image"));

        if (leftImage == null) {
            leftImage = new ImageIcon(getClass().getResource("/org/jinstaller/resources/app.png"));
        }


        initComponents();
        setLocationRelativeTo(null);
        fases = new ArrayList<InstallerFase>();
        fases.add(new JPanelStart());
        fases.add(new JPanelLicence());
        fases.add(new JPanelFolderSelection());
        setSize(810, 400);
        next();
    }

    public void next() {
        if (actualPanel != null) {
            actualPanel.setVisible(false);
            jPanelInteract.remove(actualPanel);
        }

        InstallerFase fase = fases.get(pointer);
        
        fase.setMainInstaller(this);
        fase.prepare();

        actualPanel = fases.get(pointer).getPanel();

        actualPanel.setVisible(true);

        jPanelInteract.add(actualPanel);
        changeButtoms();

    }

    private void changeButtoms() {
        if (pointer == 0) {
            jButtonPrev.setVisible(false);
        } else if (pointer == fases.size() - 1) {
            jButtonNext.setText("Finish");
            jButtonPrev.setVisible(false);
        } else {
            jButtonPrev.setVisible(!(pointer == 0));
            jButtonNext.setText("Next");
        }

    }

    public boolean hasNext() {
        return pointer < fases.size();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelMessage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelInteract = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButtonNext = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonPrev = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 400));
        setResizable(false);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(650, 60));
        jPanel1.setMinimumSize(new java.awt.Dimension(650, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 60));

        jLabelTitle.setText("Welcome of the %APPNAME% Installer");

        jLabelMessage.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelMessage.setText("Please click em next to procced");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabelMessage)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabelMessage)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setMaximumSize(new java.awt.Dimension(150, 400));
        jPanel3.setMinimumSize(new java.awt.Dimension(150, 400));
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 400));

        jLabel1.setIcon(leftImage);
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 0));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 0));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelInteract.setMaximumSize(new java.awt.Dimension(650, 250));
        jPanelInteract.setMinimumSize(new java.awt.Dimension(650, 250));
        jPanelInteract.setPreferredSize(new java.awt.Dimension(650, 250));
        jPanelInteract.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setMaximumSize(new java.awt.Dimension(650, 50));
        jPanel4.setMinimumSize(new java.awt.Dimension(650, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(650, 50));

        jButtonNext.setText("Next");
        jButtonNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonNextMousePressed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonCancelMousePressed(evt);
            }
        });

        jButtonPrev.setText("Back");
        jButtonPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonPrevMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPrev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNext)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonPrev))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelInteract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInteract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelMousePressed
        jDialogMessage.ResultType resultType =
                jDialogMessage.show(this, "Do you really want to cancel?",
                jDialogMessage.DialogType.OK_CANCEL);
        if (resultType.equals(jDialogMessage.ResultType.OK)) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonCancelMousePressed

    private void jButtonNextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNextMousePressed
        if (!locked) {
            boolean next = ((InstallerFase) actualPanel).onContinue();
            if (next) {
                pointer++;
                if (hasNext()) {
                    next();
                } else {
                    System.exit(0);
                }
            }
        }
    }//GEN-LAST:event_jButtonNextMousePressed

    private void jButtonPrevMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPrevMousePressed
        if (!locked) {
            pointer--;
            next();
        }
    }//GEN-LAST:event_jButtonPrevMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelInteract;
    // End of variables declaration//GEN-END:variables

    public void changeMessage(String message) {
        jLabelMessage.setText(MessageUtil.getMessage(message));
    }

    public void forceContine() {
        jButtonNextMousePressed(null);
    }

    private void lock(boolean lock) {
        locked = lock;
        jButtonCancel.setEnabled(lock);
        jButtonNext.setEnabled(lock);
        jButtonPrev.setEnabled(lock);
    }

    public void lock() {
        lock(true);
    }

    public void unlock() {
        lock(false);
    }

    public void changeTitle(String title) {
        jLabelTitle.setText(MessageUtil.getMessage(title));
    }
    
}
