/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jinstaller.panels;

import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jinstaller.InstallerFase;
import org.jinstaller.MainInstaller;
import org.jinstaller.jDialogMessage;
import org.jinstaller.util.FileUtil;
import org.jinstaller.util.MessageUtil;
import org.jinstaller.util.Properties;

/**
 *
 * @author luis
 */
public class JPanelTerms extends javax.swing.JPanel implements InstallerFase {

    MainInstaller main;
    String text;

    /**
     * Creates new form JPanelStart
     */
    public JPanelTerms() {
        try {
            text = MessageUtil.getMessage(FileUtil.readText(
                    Properties.getProperty("licence-file")));
        } catch (Exception e) {
            jDialogMessage.show((JFrame) main, "license file not found, \n"
                    + "please see logs to more information.");
            Logger.getLogger(this.getClass().getSimpleName()).
                    info("License file not found, add one in path of instalation"
                    + " and indicate in data.props with key:\"licence-file\"");
            
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBoxTerms = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(650, 250));
        setMinimumSize(new java.awt.Dimension(650, 250));
        setPreferredSize(new java.awt.Dimension(650, 250));

        jLabel2.setText("Please Agree this terms:");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText(text);
        jScrollPane1.setViewportView(jTextArea1);

        jCheckBoxTerms.setText("I read and agree this terms");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBoxTerms)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxTerms)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxTerms;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public boolean onContinue() {
        if(!jCheckBoxTerms.isSelected()){
            jDialogMessage.show((JFrame)main, "Please, accept the terms and check the box to continue");
            
            return false;
        }
        return true;
    }

    public void prepare() {
        setVisible(true);
    }

    public void setMainInstaller(MainInstaller main) {
        this.main = main;
    }

    public JPanel getPanel() {
        return this;
    }
}
