/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jinstaller.panels;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jinstaller.InstallerFase;
import org.jinstaller.MainInstaller;
import org.jinstaller.jDialogMessage;
import org.jinstaller.util.MessageUtil;
import org.jinstaller.util.Properties;

/**
 *
 * @author luis
 */
public class JPanelFolderSelection extends javax.swing.JPanel implements InstallerFase {

    MainInstaller main;
    File folder;

    /**
     * Creates new form JPanelStart
     */
    public JPanelFolderSelection() {
        initComponents();
        fileChooser.setVisible(false);
        folder = new File(Properties.getProperty("installaction-folder"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMessageFolder = new javax.swing.JLabel();
        jTextFieldFolder = new javax.swing.JTextField();
        jButtonFolderSelection = new javax.swing.JButton();
        fileChooser = new javax.swing.JFileChooser();

        setMaximumSize(new java.awt.Dimension(650, 250));
        setMinimumSize(new java.awt.Dimension(650, 250));
        setPreferredSize(new java.awt.Dimension(650, 250));

        jLabelMessageFolder.setText(MessageUtil.getMessage("The %application-single-name% will install in this directory"));

        jTextFieldFolder.setText(System.getProperty("user.dir"));

        jButtonFolderSelection.setText("Change");
        jButtonFolderSelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonFolderSelectionMousePressed(evt);
            }
        });

        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMessageFolder)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 24, Short.MAX_VALUE)
                        .addComponent(jTextFieldFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFolderSelection)
                        .addGap(29, 29, 29))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 66, Short.MAX_VALUE)
                    .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 67, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabelMessageFolder)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFolderSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFolderSelectionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFolderSelectionMousePressed
        
        fileChooser.setSelectedFile(folder);
        fileChooser.setVisible(true);
        int returnVal = fileChooser.showOpenDialog(null);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            folder = fileChooser.getSelectedFile();

            jTextFieldFolder.setText(folder.getAbsolutePath());

        }
        fileChooser.setVisible(false);
    }//GEN-LAST:event_jButtonFolderSelectionMousePressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButtonFolderSelection;
    private javax.swing.JLabel jLabelMessageFolder;
    private javax.swing.JTextField jTextFieldFolder;
    // End of variables declaration//GEN-END:variables

    public boolean onContinue() {
        String path = jTextFieldFolder.getText();
        Properties.put("installaction-folder", path);
        boolean valid = true;
        if (!folder.isDirectory() || !folder.canWrite()) {
            jDialogMessage.show((JFrame) main, "Please select a valid folder!",
                    jDialogMessage.DialogType.OK);
            valid = false;
        }
        return valid;
    }

    public void prepare() {
        setVisible(true);
    }

    public void setMainInstaller(MainInstaller main) {
        this.main = main;
    }

    public JPanel getPanel() {
        return this;
    }
}
